# Generated by Django 4.1.3 on 2022-11-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('duracao', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('produtor', models.CharField(max_length=100)),
                ('diretor', models.CharField(max_length=100)),
                ('elenco', models.CharField(max_length=100)),
                ('direcao', models.CharField(max_length=100)),
            ],
        ),
    ]
